/*
 * This code is for the bachelor thesis named "Towed-ROV".
 * The purpose is to build a ROV which will be towed behind a surface vessel
 * and act as a multi-sensor platform, were it shall be easy to place new 
 * sensors. There will also be a video stream from the ROV.
 * 
 * The system consists of two Raspberry Pis in the ROV that is connected to
 * several Arduino micro controllers. These micro controllers are connected to
 * feedback from the actuators, the echo sounder and extra optional sensors.
 * The external computer which is on the surface vessel is connected to a GPS,
 * echo sounder over USB, and the ROV over ethernet. It will present and
 * log data in addition to handle user commands for controlling the ROV.
 */
package ntnusubsea.gui;

import java.io.File;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 * This frame lets the user control the different inputs and outputs. Sends a
 * new command whenever a button is pressed.
 *@author Towed ROV 2019 https://ntnuopen.ntnu.no/ntnu-xmlui/handle/11250/2564356
 */
public class IOControlFrame extends javax.swing.JFrame implements Runnable, Observer {

    private Data data;
    private TCPClient client;
    private final String DIGITALOUTID = "<DigitalOut>";
    private int outputValue = 0;

    /**
     * Creates new form IOControlFrame
     *
     * @param data Data containing shared variables
     * @param client TCP client that sends commands
     */
    public IOControlFrame(Data data, TCPClient client) {
        initComponents();
        this.pack();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.data = data;
        this.client = client;
        jLabelChannel1Value.setText(data.getChannel(1));
        jLabelChannel2Value.setText(data.getChannel(2));
        jLabelChannel3Value.setText(data.getChannel(3));
        jLabelChannel4Value.setText(data.getChannel(4));
        jLabelChannel5Value.setText(data.getChannel(5));
        jLabelChannel6Value.setText(data.getChannel(6));
        jLabelChannel7Value.setText(data.getChannel(7));
        jLabelChannel8Value.setText(data.getChannel(8));
        enableIO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel9 = new javax.swing.JPanel();
        jPanelChannel5 = new javax.swing.JPanel();
        jLabelChannel5Header = new javax.swing.JLabel();
        jToggleButtonChannel5 = new javax.swing.JToggleButton();
        jLabelChannel5Value = new javax.swing.JLabel();
        jLabelOnChannel5 = new javax.swing.JLabel();
        jLabelOffChannel5 = new javax.swing.JLabel();
        jLabelIndicatorChannel5 = new javax.swing.JLabel();
        jPanelChannel6 = new javax.swing.JPanel();
        jLabelChannel6Header = new javax.swing.JLabel();
        jToggleButtonChannel6 = new javax.swing.JToggleButton();
        jLabelChannel6Value = new javax.swing.JLabel();
        jLabelOnChannel6 = new javax.swing.JLabel();
        jLabelOffChannel6 = new javax.swing.JLabel();
        jLabelIndicatorChannel6 = new javax.swing.JLabel();
        jPanelChannel7 = new javax.swing.JPanel();
        jLabelChannel7Header = new javax.swing.JLabel();
        jToggleButtonChannel7 = new javax.swing.JToggleButton();
        jLabelChannel7Value = new javax.swing.JLabel();
        jLabelOnChannel7 = new javax.swing.JLabel();
        jLabelOffChannel7 = new javax.swing.JLabel();
        jLabelIndicatorChannel7 = new javax.swing.JLabel();
        jPanelChannel8 = new javax.swing.JPanel();
        jLabelChannel8Header = new javax.swing.JLabel();
        jToggleButtonChannel8 = new javax.swing.JToggleButton();
        jLabelChannel8Value = new javax.swing.JLabel();
        jLabelOnChannel8 = new javax.swing.JLabel();
        jLabelOffChannel8 = new javax.swing.JLabel();
        jLabelIndicatorChannel8 = new javax.swing.JLabel();
        jPanelChannel1 = new javax.swing.JPanel();
        jLabelChannel1Header = new javax.swing.JLabel();
        jLabelChannel1Value = new javax.swing.JLabel();
        jToggleButtonChannel1 = new javax.swing.JToggleButton();
        jLabelIndicatorChannel1 = new javax.swing.JLabel();
        jLabelOnChannel1 = new javax.swing.JLabel();
        jLabelOffChannel1 = new javax.swing.JLabel();
        jPanelChannel2 = new javax.swing.JPanel();
        jLabelChannel2Header = new javax.swing.JLabel();
        jLabelChannel2Value = new javax.swing.JLabel();
        jToggleButtonChannel2 = new javax.swing.JToggleButton();
        jLabelIndicatorChannel2 = new javax.swing.JLabel();
        jLabelOnChannel2 = new javax.swing.JLabel();
        jLabelOffChannel2 = new javax.swing.JLabel();
        jPanelChannel3 = new javax.swing.JPanel();
        jLabelChannel3Header = new javax.swing.JLabel();
        jLabelChannel3Value = new javax.swing.JLabel();
        jToggleButtonChannel3 = new javax.swing.JToggleButton();
        jLabelIndicatorChannel3 = new javax.swing.JLabel();
        jLabelOnChannel3 = new javax.swing.JLabel();
        jLabelOffChannel3 = new javax.swing.JLabel();
        jPanelChannel4 = new javax.swing.JPanel();
        jLabelChannel4Header = new javax.swing.JLabel();
        jLabelChannel4Value = new javax.swing.JLabel();
        jToggleButtonChannel4 = new javax.swing.JToggleButton();
        jLabelIndicatorChannel4 = new javax.swing.JLabel();
        jLabelOnChannel4 = new javax.swing.JLabel();
        jLabelOffChannel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("I/O Controller");
        setBackground(new java.awt.Color(39, 44, 50));
        setForeground(new java.awt.Color(28, 28, 28));
        setResizable(false);

        jPanel9.setBackground(new java.awt.Color(39, 44, 50));

        jPanelChannel5.setBackground(new java.awt.Color(35, 39, 43));
        jPanelChannel5.setPreferredSize(new java.awt.Dimension(170, 191));

        jLabelChannel5Header.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel5Header.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel5Header.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel5Header.setText("Channel 5 (Output)");

        jToggleButtonChannel5.setBackground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel5.setForeground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-off-vertical.gif"))); // NOI18N
        jToggleButtonChannel5.setBorder(null);
        jToggleButtonChannel5.setContentAreaFilled(false);
        jToggleButtonChannel5.setEnabled(false);
        jToggleButtonChannel5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-on-vertical.gif"))); // NOI18N
        jToggleButtonChannel5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButtonChannel5ActionPerformed(evt);
            }
        });

        jLabelChannel5Value.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel5Value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel5Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel5Value.setText("jLabel2");

        jLabelOnChannel5.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOnChannel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOnChannel5.setText("On");

        jLabelOffChannel5.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOffChannel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOffChannel5.setText("Off");

        jLabelIndicatorChannel5.setBackground(new java.awt.Color(35, 39, 43));
        jLabelIndicatorChannel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/IO-Off.gif"))); // NOI18N
        jLabelIndicatorChannel5.setOpaque(true);

        javax.swing.GroupLayout jPanelChannel5Layout = new javax.swing.GroupLayout(jPanelChannel5);
        jPanelChannel5.setLayout(jPanelChannel5Layout);
        jPanelChannel5Layout.setHorizontalGroup(
            jPanelChannel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelChannel5Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelChannel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonChannel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndicatorChannel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOnChannel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelOffChannel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jLabelChannel5Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelChannel5Layout.setVerticalGroup(
            jPanelChannel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChannel5Layout.createSequentialGroup()
                .addComponent(jLabelChannel5Header, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelChannel5Value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChannel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabelOnChannel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOffChannel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButtonChannel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIndicatorChannel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelChannel6.setBackground(new java.awt.Color(35, 39, 43));
        jPanelChannel6.setPreferredSize(new java.awt.Dimension(170, 191));

        jLabelChannel6Header.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel6Header.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel6Header.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel6Header.setText("Channel 6 (Output)");

        jToggleButtonChannel6.setBackground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel6.setForeground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-off-vertical.gif"))); // NOI18N
        jToggleButtonChannel6.setBorder(null);
        jToggleButtonChannel6.setContentAreaFilled(false);
        jToggleButtonChannel6.setEnabled(false);
        jToggleButtonChannel6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-on-vertical.gif"))); // NOI18N
        jToggleButtonChannel6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButtonChannel6ActionPerformed(evt);
            }
        });

        jLabelChannel6Value.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel6Value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel6Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel6Value.setText("jLabel2");

        jLabelOnChannel6.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOnChannel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOnChannel6.setText("On");

        jLabelOffChannel6.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOffChannel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOffChannel6.setText("Off");

        jLabelIndicatorChannel6.setBackground(new java.awt.Color(35, 39, 43));
        jLabelIndicatorChannel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/IO-Off.gif"))); // NOI18N
        jLabelIndicatorChannel6.setText("jLabel26");
        jLabelIndicatorChannel6.setOpaque(true);

        javax.swing.GroupLayout jPanelChannel6Layout = new javax.swing.GroupLayout(jPanelChannel6);
        jPanelChannel6.setLayout(jPanelChannel6Layout);
        jPanelChannel6Layout.setHorizontalGroup(
            jPanelChannel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelChannel6Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelChannel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonChannel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndicatorChannel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOffChannel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabelOnChannel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jLabelChannel6Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelChannel6Layout.setVerticalGroup(
            jPanelChannel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChannel6Layout.createSequentialGroup()
                .addComponent(jLabelChannel6Header, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelChannel6Value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChannel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChannel6Layout.createSequentialGroup()
                            .addComponent(jLabelOnChannel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelOffChannel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11))
                        .addComponent(jLabelIndicatorChannel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButtonChannel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelChannel7.setBackground(new java.awt.Color(35, 39, 43));
        jPanelChannel7.setPreferredSize(new java.awt.Dimension(170, 191));

        jLabelChannel7Header.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel7Header.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel7Header.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel7Header.setText("Channel 7 (Output)");

        jToggleButtonChannel7.setBackground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel7.setForeground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-off-vertical.gif"))); // NOI18N
        jToggleButtonChannel7.setBorder(null);
        jToggleButtonChannel7.setContentAreaFilled(false);
        jToggleButtonChannel7.setEnabled(false);
        jToggleButtonChannel7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-on-vertical.gif"))); // NOI18N
        jToggleButtonChannel7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButtonChannel7ActionPerformed(evt);
            }
        });

        jLabelChannel7Value.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel7Value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel7Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel7Value.setText("jLabel2");

        jLabelOnChannel7.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOnChannel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOnChannel7.setText("On");

        jLabelOffChannel7.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOffChannel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOffChannel7.setText("Off");

        jLabelIndicatorChannel7.setBackground(new java.awt.Color(35, 39, 43));
        jLabelIndicatorChannel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/IO-Off.gif"))); // NOI18N
        jLabelIndicatorChannel7.setOpaque(true);

        javax.swing.GroupLayout jPanelChannel7Layout = new javax.swing.GroupLayout(jPanelChannel7);
        jPanelChannel7.setLayout(jPanelChannel7Layout);
        jPanelChannel7Layout.setHorizontalGroup(
            jPanelChannel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelChannel7Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelChannel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonChannel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndicatorChannel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOffChannel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabelOnChannel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jLabelChannel7Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelChannel7Layout.setVerticalGroup(
            jPanelChannel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChannel7Layout.createSequentialGroup()
                .addComponent(jLabelChannel7Header, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelChannel7Value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChannel7Layout.createSequentialGroup()
                        .addComponent(jLabelOnChannel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOffChannel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(jToggleButtonChannel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIndicatorChannel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelChannel8.setBackground(new java.awt.Color(35, 39, 43));
        jPanelChannel8.setPreferredSize(new java.awt.Dimension(170, 191));

        jLabelChannel8Header.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel8Header.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel8Header.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel8Header.setText("Channel 8 (Output)");

        jToggleButtonChannel8.setBackground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel8.setForeground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-off-vertical.gif"))); // NOI18N
        jToggleButtonChannel8.setBorder(null);
        jToggleButtonChannel8.setContentAreaFilled(false);
        jToggleButtonChannel8.setEnabled(false);
        jToggleButtonChannel8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-on-vertical.gif"))); // NOI18N
        jToggleButtonChannel8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButtonChannel8ActionPerformed(evt);
            }
        });

        jLabelChannel8Value.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel8Value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel8Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel8Value.setText("jLabel2");

        jLabelOnChannel8.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOnChannel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOnChannel8.setText("On");

        jLabelOffChannel8.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOffChannel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOffChannel8.setText("Off");

        jLabelIndicatorChannel8.setBackground(new java.awt.Color(35, 39, 43));
        jLabelIndicatorChannel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/IO-Off.gif"))); // NOI18N
        jLabelIndicatorChannel8.setOpaque(true);

        javax.swing.GroupLayout jPanelChannel8Layout = new javax.swing.GroupLayout(jPanelChannel8);
        jPanelChannel8.setLayout(jPanelChannel8Layout);
        jPanelChannel8Layout.setHorizontalGroup(
            jPanelChannel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelChannel8Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelChannel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonChannel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndicatorChannel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOffChannel8, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabelOnChannel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jLabelChannel8Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelChannel8Layout.setVerticalGroup(
            jPanelChannel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChannel8Layout.createSequentialGroup()
                .addComponent(jLabelChannel8Header, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelChannel8Value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIndicatorChannel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonChannel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChannel8Layout.createSequentialGroup()
                        .addComponent(jLabelOnChannel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOffChannel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );

        jPanelChannel1.setBackground(new java.awt.Color(35, 39, 43));
        jPanelChannel1.setPreferredSize(new java.awt.Dimension(170, 191));

        jLabelChannel1Header.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel1Header.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel1Header.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel1Header.setText("Channel 1 (Input)");

        jLabelChannel1Value.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel1Value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel1Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel1Value.setText("jLabel2");

        jToggleButtonChannel1.setBackground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel1.setForeground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-off-vertical.gif"))); // NOI18N
        jToggleButtonChannel1.setBorder(null);
        jToggleButtonChannel1.setContentAreaFilled(false);
        jToggleButtonChannel1.setEnabled(false);
        jToggleButtonChannel1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-on-vertical.gif"))); // NOI18N
        jToggleButtonChannel1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButtonChannel1ActionPerformed(evt);
            }
        });

        jLabelIndicatorChannel1.setBackground(new java.awt.Color(35, 39, 43));
        jLabelIndicatorChannel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/IO-Off.gif"))); // NOI18N
        jLabelIndicatorChannel1.setOpaque(true);

        jLabelOnChannel1.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOnChannel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOnChannel1.setText("On");

        jLabelOffChannel1.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOffChannel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOffChannel1.setText("Off");

        javax.swing.GroupLayout jPanelChannel1Layout = new javax.swing.GroupLayout(jPanelChannel1);
        jPanelChannel1.setLayout(jPanelChannel1Layout);
        jPanelChannel1Layout.setHorizontalGroup(
            jPanelChannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelChannel1Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelChannel1Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelChannel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonChannel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndicatorChannel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOffChannel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabelOnChannel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelChannel1Layout.setVerticalGroup(
            jPanelChannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChannel1Layout.createSequentialGroup()
                .addGroup(jPanelChannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIndicatorChannel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelChannel1Layout.createSequentialGroup()
                        .addComponent(jLabelChannel1Header, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelChannel1Value, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelChannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelChannel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabelOnChannel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOffChannel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChannel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButtonChannel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelChannel2.setBackground(new java.awt.Color(35, 39, 43));
        jPanelChannel2.setPreferredSize(new java.awt.Dimension(170, 191));

        jLabelChannel2Header.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel2Header.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel2Header.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel2Header.setText("Channel 2 (Input)");

        jLabelChannel2Value.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel2Value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel2Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel2Value.setText("jLabel2");

        jToggleButtonChannel2.setBackground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel2.setForeground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-off-vertical.gif"))); // NOI18N
        jToggleButtonChannel2.setBorder(null);
        jToggleButtonChannel2.setContentAreaFilled(false);
        jToggleButtonChannel2.setEnabled(false);
        jToggleButtonChannel2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-on-vertical.gif"))); // NOI18N
        jToggleButtonChannel2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButtonChannel2ActionPerformed(evt);
            }
        });

        jLabelIndicatorChannel2.setBackground(new java.awt.Color(35, 39, 43));
        jLabelIndicatorChannel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/IO-Off.gif"))); // NOI18N
        jLabelIndicatorChannel2.setOpaque(true);

        jLabelOnChannel2.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOnChannel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOnChannel2.setText("On");

        jLabelOffChannel2.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOffChannel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOffChannel2.setText("Off");

        javax.swing.GroupLayout jPanelChannel2Layout = new javax.swing.GroupLayout(jPanelChannel2);
        jPanelChannel2.setLayout(jPanelChannel2Layout);
        jPanelChannel2Layout.setHorizontalGroup(
            jPanelChannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelChannel2Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelChannel2Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelChannel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonChannel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndicatorChannel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChannel2Layout.createSequentialGroup()
                        .addComponent(jLabelOnChannel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanelChannel2Layout.createSequentialGroup()
                        .addComponent(jLabelOffChannel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanelChannel2Layout.setVerticalGroup(
            jPanelChannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChannel2Layout.createSequentialGroup()
                .addComponent(jLabelChannel2Header, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelChannel2Value, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelChannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChannel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelOnChannel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOffChannel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelChannel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelChannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIndicatorChannel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonChannel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelChannel3.setBackground(new java.awt.Color(35, 39, 43));
        jPanelChannel3.setPreferredSize(new java.awt.Dimension(170, 191));

        jLabelChannel3Header.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel3Header.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel3Header.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel3Header.setText("Channel 3 (Input)");

        jLabelChannel3Value.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel3Value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel3Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel3Value.setText("jLabel2");

        jToggleButtonChannel3.setBackground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel3.setForeground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-off-vertical.gif"))); // NOI18N
        jToggleButtonChannel3.setBorder(null);
        jToggleButtonChannel3.setContentAreaFilled(false);
        jToggleButtonChannel3.setEnabled(false);
        jToggleButtonChannel3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-on-vertical.gif"))); // NOI18N
        jToggleButtonChannel3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButtonChannel3ActionPerformed(evt);
            }
        });

        jLabelIndicatorChannel3.setBackground(new java.awt.Color(35, 39, 43));
        jLabelIndicatorChannel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/IO-Off.gif"))); // NOI18N
        jLabelIndicatorChannel3.setOpaque(true);

        jLabelOnChannel3.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOnChannel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOnChannel3.setText("On");

        jLabelOffChannel3.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOffChannel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOffChannel3.setText("Off");

        javax.swing.GroupLayout jPanelChannel3Layout = new javax.swing.GroupLayout(jPanelChannel3);
        jPanelChannel3.setLayout(jPanelChannel3Layout);
        jPanelChannel3Layout.setHorizontalGroup(
            jPanelChannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelChannel3Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelChannel3Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelChannel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonChannel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndicatorChannel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChannel3Layout.createSequentialGroup()
                        .addComponent(jLabelOnChannel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanelChannel3Layout.createSequentialGroup()
                        .addComponent(jLabelOffChannel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanelChannel3Layout.setVerticalGroup(
            jPanelChannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChannel3Layout.createSequentialGroup()
                .addGroup(jPanelChannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButtonChannel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelChannel3Layout.createSequentialGroup()
                        .addComponent(jLabelChannel3Header, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelChannel3Value, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelChannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelChannel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelIndicatorChannel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelChannel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabelOnChannel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOffChannel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanelChannel4.setBackground(new java.awt.Color(35, 39, 43));
        jPanelChannel4.setPreferredSize(new java.awt.Dimension(170, 191));

        jLabelChannel4Header.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel4Header.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel4Header.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel4Header.setText("Channel 4 (Input)");

        jLabelChannel4Value.setBackground(new java.awt.Color(28, 28, 28));
        jLabelChannel4Value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChannel4Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChannel4Value.setText("jLabel2");

        jToggleButtonChannel4.setBackground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel4.setForeground(new java.awt.Color(35, 39, 43));
        jToggleButtonChannel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-off-vertical.gif"))); // NOI18N
        jToggleButtonChannel4.setBorder(null);
        jToggleButtonChannel4.setContentAreaFilled(false);
        jToggleButtonChannel4.setEnabled(false);
        jToggleButtonChannel4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-on-vertical.gif"))); // NOI18N
        jToggleButtonChannel4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButtonChannel4ActionPerformed(evt);
            }
        });

        jLabelIndicatorChannel4.setBackground(new java.awt.Color(35, 39, 43));
        jLabelIndicatorChannel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/IO-Off.gif"))); // NOI18N
        jLabelIndicatorChannel4.setOpaque(true);

        jLabelOnChannel4.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOnChannel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOnChannel4.setText("On");

        jLabelOffChannel4.setBackground(new java.awt.Color(28, 28, 28));
        jLabelOffChannel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOffChannel4.setText("Off");

        javax.swing.GroupLayout jPanelChannel4Layout = new javax.swing.GroupLayout(jPanelChannel4);
        jPanelChannel4.setLayout(jPanelChannel4Layout);
        jPanelChannel4Layout.setHorizontalGroup(
            jPanelChannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelChannel4Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelChannel4Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelChannel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonChannel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIndicatorChannel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelChannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOffChannel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOnChannel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelChannel4Layout.setVerticalGroup(
            jPanelChannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChannel4Layout.createSequentialGroup()
                .addGroup(jPanelChannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButtonChannel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelChannel4Layout.createSequentialGroup()
                        .addComponent(jLabelChannel4Header, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelChannel4Value, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelChannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelChannel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelIndicatorChannel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelChannel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabelOnChannel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOffChannel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelChannel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelChannel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanelChannel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelChannel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelChannel4, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanelChannel6, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelChannel7, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelChannel8, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelChannel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelChannel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelChannel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelChannel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelChannel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelChannel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelChannel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelChannel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonChannel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonChannel5ActionPerformed
        try {
            if (jToggleButtonChannel5.isSelected()) {
                setBit(4, 1);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel5.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-On.gif"))));
            } else {
                setBit(4, 0);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel5.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-Off.gif"))));
            }
            System.out.println(outputValue);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jToggleButtonChannel5ActionPerformed

    private void jToggleButtonChannel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonChannel6ActionPerformed
        try {
            if (jToggleButtonChannel6.isSelected()) {
                setBit(5, 1);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel6.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-On.gif"))));
            } else {
                setBit(5, 0);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel6.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-Off.gif"))));
            }
            System.out.println(outputValue);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jToggleButtonChannel6ActionPerformed

    private void jToggleButtonChannel7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonChannel7ActionPerformed
        try {
            if (jToggleButtonChannel7.isSelected()) {
                setBit(6, 1);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel7.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-On.gif"))));
            } else {
                setBit(6, 0);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel7.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-Off.gif"))));
            }
            System.out.println(outputValue);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jToggleButtonChannel7ActionPerformed

    private void jToggleButtonChannel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonChannel8ActionPerformed
        try {
            if (jToggleButtonChannel8.isSelected()) {
                setBit(7, 1);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel8.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-On.gif"))));
            } else {
                setBit(7, 0);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel8.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-Off.gif"))));
            }
            System.out.println(outputValue);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jToggleButtonChannel8ActionPerformed

    private void jToggleButtonChannel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonChannel1ActionPerformed
        try {
            if (jToggleButtonChannel1.isSelected()) {
                setBit(0, 1);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel1.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-On.gif"))));
            } else {
                setBit(0, 0);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel1.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-Off.gif"))));
            }
            System.out.println(outputValue);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jToggleButtonChannel1ActionPerformed

    private void jToggleButtonChannel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonChannel2ActionPerformed
        try {
            if (jToggleButtonChannel2.isSelected()) {
                setBit(1, 1);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel2.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-On.gif"))));
            } else {
                setBit(1, 0);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel2.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-Off.gif"))));
            }
            System.out.println(outputValue);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jToggleButtonChannel2ActionPerformed

    private void jToggleButtonChannel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonChannel3ActionPerformed
        try {
            if (jToggleButtonChannel3.isSelected()) {
                setBit(2, 1);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel3.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-On.gif"))));
            } else {
                setBit(2, 0);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel3.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-Off.gif"))));
            }
            System.out.println(outputValue);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jToggleButtonChannel3ActionPerformed

    private void jToggleButtonChannel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonChannel4ActionPerformed
        try {
            if (jToggleButtonChannel4.isSelected()) {
                setBit(3, 1);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel4.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-On.gif"))));
            } else {
                setBit(3, 0);
                //client.sendCommand(DIGITALOUTID + outputValue);
                jLabelIndicatorChannel4.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/IO-Off.gif"))));
            }
            System.out.println(outputValue);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jToggleButtonChannel4ActionPerformed

    /**
     * Enables the I/O buttons
     */
    public void enableIO() {
        jToggleButtonChannel1.setEnabled(true);
        jToggleButtonChannel2.setEnabled(true);
        jToggleButtonChannel3.setEnabled(true);
        jToggleButtonChannel4.setEnabled(true);
        jToggleButtonChannel5.setEnabled(true);
        jToggleButtonChannel6.setEnabled(true);
        jToggleButtonChannel7.setEnabled(true);
        jToggleButtonChannel8.setEnabled(true);
    }

    /**
     * Disables the I/O buttons
     */
    public void disableIO() {
        jToggleButtonChannel1.setEnabled(false);
        jToggleButtonChannel2.setEnabled(false);
        jToggleButtonChannel3.setEnabled(false);
        jToggleButtonChannel4.setEnabled(false);
        jToggleButtonChannel5.setEnabled(false);
        jToggleButtonChannel6.setEnabled(false);
        jToggleButtonChannel7.setEnabled(false);
        jToggleButtonChannel8.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelChannel1Header;
    private javax.swing.JLabel jLabelChannel1Value;
    private javax.swing.JLabel jLabelChannel2Header;
    private javax.swing.JLabel jLabelChannel2Value;
    private javax.swing.JLabel jLabelChannel3Header;
    private javax.swing.JLabel jLabelChannel3Value;
    private javax.swing.JLabel jLabelChannel4Header;
    private javax.swing.JLabel jLabelChannel4Value;
    private javax.swing.JLabel jLabelChannel5Header;
    private javax.swing.JLabel jLabelChannel5Value;
    private javax.swing.JLabel jLabelChannel6Header;
    private javax.swing.JLabel jLabelChannel6Value;
    private javax.swing.JLabel jLabelChannel7Header;
    private javax.swing.JLabel jLabelChannel7Value;
    private javax.swing.JLabel jLabelChannel8Header;
    private javax.swing.JLabel jLabelChannel8Value;
    private javax.swing.JLabel jLabelIndicatorChannel1;
    private javax.swing.JLabel jLabelIndicatorChannel2;
    private javax.swing.JLabel jLabelIndicatorChannel3;
    private javax.swing.JLabel jLabelIndicatorChannel4;
    private javax.swing.JLabel jLabelIndicatorChannel5;
    private javax.swing.JLabel jLabelIndicatorChannel6;
    private javax.swing.JLabel jLabelIndicatorChannel7;
    private javax.swing.JLabel jLabelIndicatorChannel8;
    private javax.swing.JLabel jLabelOffChannel1;
    private javax.swing.JLabel jLabelOffChannel2;
    private javax.swing.JLabel jLabelOffChannel3;
    private javax.swing.JLabel jLabelOffChannel4;
    private javax.swing.JLabel jLabelOffChannel5;
    private javax.swing.JLabel jLabelOffChannel6;
    private javax.swing.JLabel jLabelOffChannel7;
    private javax.swing.JLabel jLabelOffChannel8;
    private javax.swing.JLabel jLabelOnChannel1;
    private javax.swing.JLabel jLabelOnChannel2;
    private javax.swing.JLabel jLabelOnChannel3;
    private javax.swing.JLabel jLabelOnChannel4;
    private javax.swing.JLabel jLabelOnChannel5;
    private javax.swing.JLabel jLabelOnChannel6;
    private javax.swing.JLabel jLabelOnChannel7;
    private javax.swing.JLabel jLabelOnChannel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelChannel1;
    private javax.swing.JPanel jPanelChannel2;
    private javax.swing.JPanel jPanelChannel3;
    private javax.swing.JPanel jPanelChannel4;
    private javax.swing.JPanel jPanelChannel5;
    private javax.swing.JPanel jPanelChannel6;
    private javax.swing.JPanel jPanelChannel7;
    private javax.swing.JPanel jPanelChannel8;
    private javax.swing.JToggleButton jToggleButtonChannel1;
    private javax.swing.JToggleButton jToggleButtonChannel2;
    private javax.swing.JToggleButton jToggleButtonChannel3;
    private javax.swing.JToggleButton jToggleButtonChannel4;
    private javax.swing.JToggleButton jToggleButtonChannel5;
    private javax.swing.JToggleButton jToggleButtonChannel6;
    private javax.swing.JToggleButton jToggleButtonChannel7;
    private javax.swing.JToggleButton jToggleButtonChannel8;
    // End of variables declaration//GEN-END:variables

    /**
     * Runs the IOControlFrame thread.
     */
    @Override
    public void run() {
        this.setVisible(false);
    }

    /**
     * Updates the channel values by observing the object
     *
     * @param o
     * @param arg
     */
    @Override
    public void update(Observable o, Object arg) {
        jLabelChannel1Value.setText(data.getChannel(1));
        jLabelChannel2Value.setText(data.getChannel(2));
        jLabelChannel3Value.setText(data.getChannel(3));
        jLabelChannel4Value.setText(data.getChannel(4));
    }

    /**
     * Sets the given value to the given bit
     *
     * @param bit the given bit
     * @param value the given value
     */
    private void setBit(int bit, int value) {
        if (value == 0) {
            outputValue = outputValue & ~(1 << bit);
        } else {
            outputValue = outputValue | (1 << bit);
        }
    }
}
